#!/usr/bin/env bash
# =============================================================================
#  IoMT CardioAI — Single-File Deployment Script
#  Version  : 1.0.0
#  Requires : bash 4+, docker (optional), kubectl (optional)
# =============================================================================
#
#  USAGE
#  -----
#    chmod +x deploy_iomt_cardioai.sh
#    ./deploy_iomt_cardioai.sh [COMMAND]
#
#  COMMANDS
#  --------
#    generate      Write all deployment artefacts to ./deploy/
#    docker        Build Docker image and run container
#    compose       Start full stack with docker-compose
#    k8s           Apply Kubernetes manifests (requires kubectl)
#    systemd       Install and start systemd service (requires sudo)
#    health        Hit the /health endpoint and print bridge status
#    logs          Tail logs for the running container / service
#    stop          Gracefully stop whichever runtime is active
#    help          Show this message
#
#  ENVIRONMENT VARIABLES  (required before running)
#  --------------------------------------------------
#    IOMT_SERVER_WS_URL      wss://iomt.hospital.local/stream
#    CARDIOAI_BACKEND_ID     cardioai-prod-01
#    IOMT_SHARED_SECRET      <32+ char secret — from Vault / SSM>
#    IOMT_JWT_SECRET         <32+ char secret — from Vault / SSM>
#
#  All other variables are optional — see .env.example generated by
#  the `generate` command for the full list with defaults.
#
# =============================================================================

set -euo pipefail

# ─── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

log()  { echo -e "${GREEN}[✓]${NC} $*"; }
info() { echo -e "${BLUE}[i]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[✗]${NC} $*" >&2; }
hdr()  { echo -e "\n${BOLD}${CYAN}══ $* ══${NC}"; }

# ─── Constants ────────────────────────────────────────────────────────────────
IMAGE_NAME="cardioai"
IMAGE_TAG="${IMAGE_TAG:-latest}"
CONTAINER_NAME="cardioai-production"
DEPLOY_DIR="./deploy"
SERVICE_NAME="cardioai"
SERVICE_USER="cardioai"
APP_DIR="/opt/cardioai"
HEALTH_PORT="${CARDIOAI_HEALTH_PORT:-8080}"
WS_PORT="${CARDIOAI_WS_PORT:-8765}"

# =============================================================================
#  COMMAND: generate — write all artefacts to ./deploy/
# =============================================================================
cmd_generate() {
    hdr "Generating deployment artefacts → ${DEPLOY_DIR}/"
    mkdir -p "${DEPLOY_DIR}/k8s"

    # ── .env.example ─────────────────────────────────────────────────────────
    cat > "${DEPLOY_DIR}/.env.example" << 'ENV'
# ============================================================
# IoMT CardioAI — Environment Configuration
# Copy to .env and fill in real values before deploying.
# NEVER commit .env to source control.
# ============================================================

# ── Required secrets (inject via Vault / AWS SSM / GCP Secret Manager) ──────
IOMT_SHARED_SECRET=REPLACE_WITH_VAULT_SECRET_MIN_32_CHARS
IOMT_JWT_SECRET=REPLACE_WITH_VAULT_JWT_SECRET_MIN_32_CHARS

# ── Required service identity ────────────────────────────────────────────────
IOMT_SERVER_WS_URL=wss://iomt.hospital.local/stream
CARDIOAI_BACKEND_ID=cardioai-prod-01

# ── Optional — IoMT server ───────────────────────────────────────────────────
IOMT_SERVER_REST_URL=https://iomt.hospital.local/api/v1
IOMT_SERVER_ID=IOMT-SRV-001

# ── Optional — CardioAI WebSocket listener ───────────────────────────────────
CARDIOAI_WS_HOST=0.0.0.0
CARDIOAI_WS_PORT=8765
CARDIOAI_HEALTH_PORT=8080

# ── Optional — Security ──────────────────────────────────────────────────────
JWT_ALGORITHM=HS256
TOKEN_TTL_SECONDS=3600

# ── Optional — Streaming & reliability ──────────────────────────────────────
RPM_POLL_INTERVAL_SEC=1.0
HEARTBEAT_INTERVAL_SEC=10.0
RECONNECT_MAX_ATTEMPTS=5
RECONNECT_BASE_DELAY_SEC=2.0
INBOUND_QUEUE_MAXSIZE=2000

# ── Optional — Observability ─────────────────────────────────────────────────
LOG_LEVEL=INFO
LOG_FORMAT=json
ENV
    log "Generated ${DEPLOY_DIR}/.env.example"

    # ── requirements.txt ─────────────────────────────────────────────────────
    cat > "${DEPLOY_DIR}/requirements.txt" << 'REQ'
websockets>=12.0
aiohttp>=3.9
PyJWT>=2.8
numpy>=1.26
REQ
    log "Generated ${DEPLOY_DIR}/requirements.txt"

    # ── Dockerfile ───────────────────────────────────────────────────────────
    cat > "${DEPLOY_DIR}/Dockerfile" << 'DOCKERFILE'
# ── Stage 1: dependency builder ───────────────────────────────────────────────
FROM python:3.12-slim AS builder

WORKDIR /build
COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir --prefix=/install -r requirements.txt

# ── Stage 2: production image ─────────────────────────────────────────────────
FROM python:3.12-slim

# Security: run as non-root
RUN groupadd --gid 1001 cardioai \
 && useradd  --uid 1001 --gid cardioai --no-create-home --shell /bin/false cardioai

WORKDIR /app

# Copy installed packages from builder
COPY --from=builder /install /usr/local

# Copy application files
COPY iomt_cardioai_production.py .
COPY IoMT_implementation.py      .
COPY IoMT_clinical_workflow.py   .
COPY IoMT_gcp_compduide.py       .

# Fix ownership
RUN chown -R cardioai:cardioai /app

USER cardioai

# Observability defaults
ENV LOG_FORMAT=json \
    LOG_LEVEL=INFO  \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

# Health check probe
HEALTHCHECK --interval=30s --timeout=10s --start-period=15s --retries=3 \
    CMD python - <<'EOF'
import urllib.request, sys
try:
    urllib.request.urlopen("http://localhost:8080/health", timeout=8)
    sys.exit(0)
except Exception:
    sys.exit(1)
EOF

EXPOSE 8765 8080

CMD ["python", "-u", "iomt_cardioai_production.py"]
DOCKERFILE
    log "Generated ${DEPLOY_DIR}/Dockerfile"

    # ── docker-compose.yml ───────────────────────────────────────────────────
    cat > "${DEPLOY_DIR}/docker-compose.yml" << 'COMPOSE'
# docker-compose.yml — IoMT CardioAI full stack
# Run:  docker-compose up -d
# Stop: docker-compose down

version: "3.9"

services:

  cardioai:
    build:
      context: .
      dockerfile: Dockerfile
    image: cardioai:latest
    container_name: cardioai-production
    restart: unless-stopped

    # Secrets injected via .env — never committed to source control
    env_file: .env

    ports:
      - "${CARDIOAI_WS_PORT:-8765}:8765"
      - "${CARDIOAI_HEALTH_PORT:-8080}:8080"

    volumes:
      - cardioai_logs:/app/logs

    networks:
      - cardioai_net

    healthcheck:
      test: ["CMD", "python", "-c",
             "import urllib.request; urllib.request.urlopen('http://localhost:8080/health', timeout=8)"]
      interval: 30s
      timeout: 10s
      retries:  3
      start_period: 15s

    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

    # Limit blast radius
    deploy:
      resources:
        limits:
          cpus:   "1.0"
          memory: "512M"
        reservations:
          cpus:   "0.25"
          memory: "256M"

  # ── Prometheus metrics scraper (optional) ───────────────────────────────────
  prometheus:
    image: prom/prometheus:latest
    container_name: cardioai-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - cardioai_net
    profiles:
      - monitoring   # only started with: docker-compose --profile monitoring up

volumes:
  cardioai_logs:
  prometheus_data:

networks:
  cardioai_net:
    driver: bridge
COMPOSE
    log "Generated ${DEPLOY_DIR}/docker-compose.yml"

    # ── prometheus.yml (optional companion) ──────────────────────────────────
    cat > "${DEPLOY_DIR}/prometheus.yml" << 'PROM'
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: cardioai
    static_configs:
      - targets: ["cardioai:8080"]
    metrics_path: /metrics
PROM
    log "Generated ${DEPLOY_DIR}/prometheus.yml"

    # ── Kubernetes manifests ──────────────────────────────────────────────────

    # namespace.yaml
    cat > "${DEPLOY_DIR}/k8s/namespace.yaml" << 'K8SNS'
apiVersion: v1
kind: Namespace
metadata:
  name: cardioai
  labels:
    app.kubernetes.io/name: cardioai
K8SNS

    # secret.yaml  (placeholder — fill via Vault operator or kubectl create secret)
    cat > "${DEPLOY_DIR}/k8s/secret.yaml" << 'K8SSEC'
# IMPORTANT: Do NOT commit real secrets here.
# In production, populate via:
#   kubectl create secret generic cardioai-secrets \
#     --namespace=cardioai \
#     --from-literal=shared_secret="$(vault kv get -field=shared_secret secret/cardioai)" \
#     --from-literal=jwt_secret="$(vault kv get -field=jwt_secret secret/cardioai)"
#
# Or use the Vault Agent Injector / External Secrets Operator.

apiVersion: v1
kind: Secret
metadata:
  name: cardioai-secrets
  namespace: cardioai
type: Opaque
stringData:
  shared_secret: "REPLACE_VIA_VAULT"
  jwt_secret:    "REPLACE_VIA_VAULT"
K8SSEC

    # configmap.yaml
    cat > "${DEPLOY_DIR}/k8s/configmap.yaml" << 'K8SCM'
apiVersion: v1
kind: ConfigMap
metadata:
  name: cardioai-config
  namespace: cardioai
data:
  IOMT_SERVER_WS_URL:       "wss://iomt.hospital.local/stream"
  IOMT_SERVER_REST_URL:     "https://iomt.hospital.local/api/v1"
  IOMT_SERVER_ID:           "IOMT-SRV-001"
  CARDIOAI_BACKEND_ID:      "cardioai-prod-01"
  CARDIOAI_WS_HOST:         "0.0.0.0"
  CARDIOAI_WS_PORT:         "8765"
  CARDIOAI_HEALTH_PORT:     "8080"
  JWT_ALGORITHM:            "HS256"
  TOKEN_TTL_SECONDS:        "3600"
  RPM_POLL_INTERVAL_SEC:    "1.0"
  HEARTBEAT_INTERVAL_SEC:   "10.0"
  RECONNECT_MAX_ATTEMPTS:   "5"
  RECONNECT_BASE_DELAY_SEC: "2.0"
  INBOUND_QUEUE_MAXSIZE:    "2000"
  LOG_LEVEL:                "INFO"
  LOG_FORMAT:               "json"
K8SCM

    # deployment.yaml
    cat > "${DEPLOY_DIR}/k8s/deployment.yaml" << 'K8SDEP'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardioai
  namespace: cardioai
  labels:
    app.kubernetes.io/name:    cardioai
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cardioai
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge:       1
      maxUnavailable: 0    # zero-downtime rolling updates
  template:
    metadata:
      labels:
        app: cardioai
      annotations:
        # Force pod restart when secret changes
        checksum/secret: "placeholder-updated-by-ci"
    spec:
      serviceAccountName: cardioai
      securityContext:
        runAsNonRoot: true
        runAsUser:    1001
        runAsGroup:   1001
        fsGroup:      1001

      containers:
      - name: cardioai
        image: cardioai:latest
        imagePullPolicy: Always

        # Non-root, read-only root filesystem
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem:   true
          capabilities:
            drop: ["ALL"]

        ports:
        - name: websocket
          containerPort: 8765
          protocol: TCP
        - name: health
          containerPort: 8080
          protocol: TCP

        # Config from ConfigMap
        envFrom:
        - configMapRef:
            name: cardioai-config

        # Secrets injected individually (not envFrom to avoid bulk exposure)
        env:
        - name: IOMT_SHARED_SECRET
          valueFrom:
            secretKeyRef:
              name: cardioai-secrets
              key:  shared_secret
        - name: IOMT_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: cardioai-secrets
              key:  jwt_secret

        resources:
          requests:
            cpu:    "250m"
            memory: "256Mi"
          limits:
            cpu:    "500m"
            memory: "512Mi"

        livenessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 15
          periodSeconds:       30
          failureThreshold:     3

        readinessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 10
          periodSeconds:       10
          failureThreshold:     3

        volumeMounts:
        - name: tmp
          mountPath: /tmp

      volumes:
      - name: tmp
        emptyDir: {}

      # Spread pods across nodes for HA
      topologySpreadConstraints:
      - maxSkew:           1
        topologyKey:       kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: cardioai
K8SDEP

    # service.yaml
    cat > "${DEPLOY_DIR}/k8s/service.yaml" << 'K8SSVC'
apiVersion: v1
kind: Service
metadata:
  name: cardioai
  namespace: cardioai
  labels:
    app.kubernetes.io/name: cardioai
spec:
  selector:
    app: cardioai
  ports:
  - name: websocket
    port: 8765
    targetPort: websocket
    protocol: TCP
  - name: health
    port: 8080
    targetPort: health
    protocol: TCP
  type: ClusterIP
K8SSVC

    # hpa.yaml
    cat > "${DEPLOY_DIR}/k8s/hpa.yaml" << 'K8SHPA'
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cardioai
  namespace: cardioai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cardioai
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type:               Utilization
        averageUtilization: 65
  - type: Resource
    resource:
      name: memory
      target:
        type:               Utilization
        averageUtilization: 75
K8SHPA

    # rbac.yaml
    cat > "${DEPLOY_DIR}/k8s/rbac.yaml" << 'K8SRBAC'
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cardioai
  namespace: cardioai
  labels:
    app.kubernetes.io/name: cardioai
---
# Minimal RBAC: read-only access to own secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cardioai-role
  namespace: cardioai
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["cardioai-secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cardioai-rolebinding
  namespace: cardioai
subjects:
- kind:      ServiceAccount
  name:      cardioai
  namespace: cardioai
roleRef:
  kind:     Role
  name:     cardioai-role
  apiGroup: rbac.authorization.k8s.io
K8SRBAC

    # networkpolicy.yaml
    cat > "${DEPLOY_DIR}/k8s/networkpolicy.yaml" << 'K8SNP'
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cardioai-netpol
  namespace: cardioai
spec:
  podSelector:
    matchLabels:
      app: cardioai
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 8765   # WebSocket
    - port: 8080   # Health
  egress:
  - ports:
    - port: 443    # Outbound TLS (IoMT server wss://)
    - port: 8765   # IoMT WebSocket
K8SNP

    # kustomization.yaml
    cat > "${DEPLOY_DIR}/k8s/kustomization.yaml" << 'K8SKUST'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cardioai

resources:
  - namespace.yaml
  - rbac.yaml
  - secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - networkpolicy.yaml
K8SKUST
    log "Generated ${DEPLOY_DIR}/k8s/ (8 manifests)"

    # ── systemd unit ──────────────────────────────────────────────────────────
    cat > "${DEPLOY_DIR}/cardioai.service" << SERVICE
[Unit]
Description=IoMT CardioAI Production Service
Documentation=https://cardioai.health/docs
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=120
StartLimitBurst=5

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_USER}
WorkingDirectory=${APP_DIR}
EnvironmentFile=${APP_DIR}/.env

ExecStart=/usr/bin/python3 -u ${APP_DIR}/iomt_cardioai_production.py
ExecReload=/bin/kill -HUP \$MAINPID

Restart=on-failure
RestartSec=5s
TimeoutStartSec=30
TimeoutStopSec=30
KillMode=mixed
KillSignal=SIGTERM

# Security hardening
NoNewPrivileges=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths=${APP_DIR}/logs
CapabilityBoundingSet=

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=cardioai

[Install]
WantedBy=multi-user.target
SERVICE
    log "Generated ${DEPLOY_DIR}/cardioai.service"

    # ── healthcheck.sh ────────────────────────────────────────────────────────
    cat > "${DEPLOY_DIR}/healthcheck.sh" << 'HC'
#!/usr/bin/env bash
# Standalone health probe — usable from CI, monitoring scripts, or cron.
set -euo pipefail

HOST="${CARDIOAI_HEALTH_HOST:-localhost}"
PORT="${CARDIOAI_HEALTH_PORT:-8080}"
TIMEOUT="${HEALTH_TIMEOUT:-10}"
URL="http://${HOST}:${PORT}/health"

echo "Probing ${URL} ..."
RESPONSE=$(curl -sf --max-time "${TIMEOUT}" "${URL}" 2>/dev/null) || {
    echo "UNHEALTHY — no response from ${URL}"
    exit 1
}

echo "${RESPONSE}" | python3 -m json.tool
echo ""

# Check queue depth warning
QUEUE=$(echo "${RESPONSE}" | python3 -c "
import sys, json
d = json.load(sys.stdin)
print(d.get('queue_depth', 0))
")

if [ "${QUEUE}" -gt 1000 ]; then
    echo "WARNING: queue_depth=${QUEUE} — back-pressure building"
fi

echo "HEALTHY"
HC
    chmod +x "${DEPLOY_DIR}/healthcheck.sh"
    log "Generated ${DEPLOY_DIR}/healthcheck.sh"

    # ── .dockerignore ─────────────────────────────────────────────────────────
    cat > "${DEPLOY_DIR}/.dockerignore" << 'DI'
.env
*.pyc
__pycache__/
.git/
.github/
*.md
tests/
*.sh
deploy/
DI
    log "Generated ${DEPLOY_DIR}/.dockerignore"

    # ── .gitignore ────────────────────────────────────────────────────────────
    cat > "${DEPLOY_DIR}/.gitignore" << 'GI'
.env
*.pyc
__pycache__/
logs/
*.log
GI
    log "Generated ${DEPLOY_DIR}/.gitignore"

    # ── Makefile ──────────────────────────────────────────────────────────────
    cat > "${DEPLOY_DIR}/Makefile" << 'MK'
.PHONY: build run stop compose-up compose-down k8s-apply k8s-delete health logs

IMAGE   ?= cardioai
TAG     ?= latest
NS      ?= cardioai

build:
	docker build -t $(IMAGE):$(TAG) .

run: build
	docker run -d \
	  --name cardioai-production \
	  --restart unless-stopped \
	  --env-file .env \
	  -p 8765:8765 \
	  -p 8080:8080 \
	  $(IMAGE):$(TAG)

stop:
	docker stop cardioai-production || true
	docker rm   cardioai-production || true

compose-up:
	docker-compose up -d --build

compose-down:
	docker-compose down

k8s-apply:
	kubectl apply -k k8s/

k8s-delete:
	kubectl delete -k k8s/

health:
	./healthcheck.sh

logs:
	docker logs -f cardioai-production 2>/dev/null \
	  || journalctl -u cardioai -f
MK
    log "Generated ${DEPLOY_DIR}/Makefile"

    hdr "All artefacts written to ${DEPLOY_DIR}/"
    echo ""
    echo "  ${DEPLOY_DIR}/"
    echo "  ├── .env.example          ← copy to .env, fill in secrets"
    echo "  ├── .gitignore"
    echo "  ├── .dockerignore"
    echo "  ├── requirements.txt"
    echo "  ├── Dockerfile             ← multi-stage, non-root"
    echo "  ├── docker-compose.yml     ← full stack with optional Prometheus"
    echo "  ├── prometheus.yml"
    echo "  ├── cardioai.service       ← systemd unit"
    echo "  ├── healthcheck.sh"
    echo "  ├── Makefile"
    echo "  └── k8s/"
    echo "      ├── kustomization.yaml"
    echo "      ├── namespace.yaml"
    echo "      ├── rbac.yaml"
    echo "      ├── secret.yaml        ← REPLACE via Vault before applying"
    echo "      ├── configmap.yaml"
    echo "      ├── deployment.yaml    ← 2 replicas, rolling update, HPA"
    echo "      ├── service.yaml"
    echo "      ├── hpa.yaml           ← scales 2→8 on CPU/memory"
    echo "      └── networkpolicy.yaml"
    echo ""
    warn "Next step: cp ${DEPLOY_DIR}/.env.example ${DEPLOY_DIR}/.env && fill in secrets"
}

# =============================================================================
#  COMMAND: docker — build and run a single container
# =============================================================================
cmd_docker() {
    hdr "Docker Build & Run"

    _check_secrets
    _assert_cmd docker

    info "Building image ${IMAGE_NAME}:${IMAGE_TAG} ..."
    docker build -t "${IMAGE_NAME}:${IMAGE_TAG}" "${DEPLOY_DIR}"
    log "Image built: ${IMAGE_NAME}:${IMAGE_TAG}"

    # Stop existing container if running
    docker stop "${CONTAINER_NAME}" 2>/dev/null || true
    docker rm   "${CONTAINER_NAME}" 2>/dev/null || true

    info "Starting container ${CONTAINER_NAME} ..."
    docker run -d \
        --name "${CONTAINER_NAME}" \
        --restart unless-stopped \
        -e "IOMT_SERVER_WS_URL=${IOMT_SERVER_WS_URL}" \
        -e "CARDIOAI_BACKEND_ID=${CARDIOAI_BACKEND_ID}" \
        -e "IOMT_SHARED_SECRET=${IOMT_SHARED_SECRET}" \
        -e "IOMT_JWT_SECRET=${IOMT_JWT_SECRET}" \
        -e "LOG_FORMAT=json" \
        -e "LOG_LEVEL=${LOG_LEVEL:-INFO}" \
        -p "${WS_PORT}:8765" \
        -p "${HEALTH_PORT}:8080" \
        "${IMAGE_NAME}:${IMAGE_TAG}"

    log "Container started: ${CONTAINER_NAME}"
    info "WebSocket: ws://localhost:${WS_PORT}"
    info "Health:    http://localhost:${HEALTH_PORT}/health"
    info "Logs:      docker logs -f ${CONTAINER_NAME}"
}

# =============================================================================
#  COMMAND: compose — start full stack with docker-compose
# =============================================================================
cmd_compose() {
    hdr "Docker Compose Up"

    _check_secrets
    _assert_cmd docker

    if [[ ! -f "${DEPLOY_DIR}/.env" ]]; then
        err ".env not found. Run: cp ${DEPLOY_DIR}/.env.example ${DEPLOY_DIR}/.env"
        err "Then fill in your secrets before running compose."
        exit 1
    fi

    info "Starting stack with docker-compose ..."
    (cd "${DEPLOY_DIR}" && docker compose up -d --build)
    log "Stack started"
    info "Health: http://localhost:${HEALTH_PORT}/health"
}

# =============================================================================
#  COMMAND: k8s — apply Kubernetes manifests
# =============================================================================
cmd_k8s() {
    hdr "Kubernetes Deployment"

    _assert_cmd kubectl

    # Verify secret placeholder has been replaced
    if grep -q "REPLACE_VIA_VAULT" "${DEPLOY_DIR}/k8s/secret.yaml" 2>/dev/null; then
        warn "secret.yaml still contains placeholder values."
        warn "For production, populate secrets via:"
        warn "  kubectl create secret generic cardioai-secrets \\"
        warn "    --namespace=cardioai \\"
        warn "    --from-literal=shared_secret=\"\$(vault kv get -field=shared_secret secret/cardioai)\" \\"
        warn "    --from-literal=jwt_secret=\"\$(vault kv get -field=jwt_secret secret/cardioai)\""
        echo ""
        read -r -p "Continue anyway? (not recommended for production) [y/N] " yn
        [[ "${yn}" =~ ^[Yy]$ ]] || { info "Aborted."; exit 0; }
    fi

    info "Applying manifests from ${DEPLOY_DIR}/k8s/ ..."
    kubectl apply -k "${DEPLOY_DIR}/k8s/"

    info "Waiting for rollout ..."
    kubectl rollout status deployment/cardioai -n cardioai --timeout=120s

    log "Deployment complete"
    kubectl get pods -n cardioai -o wide
}

# =============================================================================
#  COMMAND: systemd — install and enable systemd service
# =============================================================================
cmd_systemd() {
    hdr "Systemd Service Installation"

    if [[ $EUID -ne 0 ]]; then
        err "systemd installation requires root. Re-run with sudo."
        exit 1
    fi

    _check_secrets

    # Create user
    if ! id "${SERVICE_USER}" &>/dev/null; then
        useradd --system --no-create-home --shell /bin/false "${SERVICE_USER}"
        log "Created system user: ${SERVICE_USER}"
    fi

    # Create app directory
    mkdir -p "${APP_DIR}/logs"
    chown -R "${SERVICE_USER}:${SERVICE_USER}" "${APP_DIR}"

    # Copy application files (assumes they are in CWD)
    for f in iomt_cardioai_production.py IoMT_implementation.py \
              IoMT_clinical_workflow.py IoMT_gcp_compduide.py; do
        if [[ -f "./${f}" ]]; then
            cp "./${f}" "${APP_DIR}/"
            log "Copied ${f} → ${APP_DIR}/"
        else
            warn "${f} not found in current directory — copy manually to ${APP_DIR}/"
        fi
    done

    # Write .env
    if [[ ! -f "${APP_DIR}/.env" ]]; then
        cat > "${APP_DIR}/.env" << ENVFILE
IOMT_SERVER_WS_URL=${IOMT_SERVER_WS_URL:-wss://iomt.hospital.local/stream}
CARDIOAI_BACKEND_ID=${CARDIOAI_BACKEND_ID:-cardioai-prod-01}
IOMT_SHARED_SECRET=${IOMT_SHARED_SECRET}
IOMT_JWT_SECRET=${IOMT_JWT_SECRET}
LOG_FORMAT=json
LOG_LEVEL=${LOG_LEVEL:-INFO}
ENVFILE
        chmod 600 "${APP_DIR}/.env"
        chown "${SERVICE_USER}:${SERVICE_USER}" "${APP_DIR}/.env"
        log "Written ${APP_DIR}/.env (mode 600)"
    else
        info "${APP_DIR}/.env already exists — not overwritten"
    fi

    # Install dependencies
    pip3 install --quiet websockets aiohttp pyjwt numpy
    log "Python dependencies installed"

    # Install service unit
    cp "${DEPLOY_DIR}/cardioai.service" /etc/systemd/system/cardioai.service
    systemctl daemon-reload
    systemctl enable cardioai
    systemctl restart cardioai
    systemctl status cardioai --no-pager

    log "Service installed and started"
    info "Logs: journalctl -u cardioai -f"
}

# =============================================================================
#  COMMAND: health — probe the /health endpoint
# =============================================================================
cmd_health() {
    hdr "Health Check"

    _assert_cmd curl

    URL="http://localhost:${HEALTH_PORT}/health"
    info "Probing ${URL} ..."

    RESPONSE=$(curl -sf --max-time 10 "${URL}") || {
        err "UNHEALTHY — no response from ${URL}"
        exit 1
    }

    echo "${RESPONSE}" | python3 -m json.tool 2>/dev/null || echo "${RESPONSE}"
    echo ""
    log "HEALTHY"
}

# =============================================================================
#  COMMAND: logs — tail logs
# =============================================================================
cmd_logs() {
    if docker ps --format '{{.Names}}' 2>/dev/null | grep -q "${CONTAINER_NAME}"; then
        docker logs -f "${CONTAINER_NAME}"
    elif systemctl is-active cardioai &>/dev/null; then
        journalctl -u cardioai -f
    else
        err "No running cardioai container or systemd service found."
        exit 1
    fi
}

# =============================================================================
#  COMMAND: stop — gracefully stop the service
# =============================================================================
cmd_stop() {
    hdr "Stopping IoMT CardioAI"

    # Docker
    if docker ps --format '{{.Names}}' 2>/dev/null | grep -q "${CONTAINER_NAME}"; then
        docker stop "${CONTAINER_NAME}"
        docker rm   "${CONTAINER_NAME}"
        log "Docker container stopped"
    fi

    # Compose
    if [[ -f "${DEPLOY_DIR}/docker-compose.yml" ]]; then
        (cd "${DEPLOY_DIR}" && docker compose down 2>/dev/null || true)
    fi

    # Systemd
    if systemctl is-active cardioai &>/dev/null 2>&1; then
        systemctl stop cardioai
        log "Systemd service stopped"
    fi

    log "Done"
}

# =============================================================================
#  HELPERS
# =============================================================================
_assert_cmd() {
    command -v "$1" &>/dev/null || {
        err "Required command not found: $1"
        exit 1
    }
}

_check_secrets() {
    local missing=0
    for var in IOMT_SERVER_WS_URL CARDIOAI_BACKEND_ID IOMT_SHARED_SECRET IOMT_JWT_SECRET; do
        if [[ -z "${!var:-}" ]]; then
            err "Required environment variable not set: ${var}"
            missing=1
        fi
    done
    if [[ "${missing}" -eq 1 ]]; then
        echo ""
        err "Set the missing variables and re-run."
        err "Example:"
        err "  export IOMT_SERVER_WS_URL='wss://iomt.hospital.local/stream'"
        err "  export CARDIOAI_BACKEND_ID='cardioai-prod-01'"
        err "  export IOMT_SHARED_SECRET=\"\$(vault kv get -field=shared_secret secret/cardioai)\""
        err "  export IOMT_JWT_SECRET=\"\$(vault kv get -field=jwt_secret secret/cardioai)\""
        exit 1
    fi
}

cmd_help() {
    cat << HELP

${BOLD}IoMT CardioAI — Deployment Script${NC}

${BOLD}USAGE${NC}
  ./deploy_iomt_cardioai.sh [COMMAND]

${BOLD}COMMANDS${NC}
  ${GREEN}generate${NC}   Write all deployment artefacts to ./deploy/
  ${GREEN}docker${NC}     Build Docker image and run single container
  ${GREEN}compose${NC}    Start full stack with docker-compose
  ${GREEN}k8s${NC}        Apply Kubernetes manifests (kubectl required)
  ${GREEN}systemd${NC}    Install systemd service (sudo required)
  ${GREEN}health${NC}     Probe /health endpoint and print bridge status
  ${GREEN}logs${NC}       Tail logs (container or systemd)
  ${GREEN}stop${NC}       Gracefully stop any running instance
  ${GREEN}help${NC}       Show this message

${BOLD}REQUIRED ENVIRONMENT VARIABLES${NC}
  IOMT_SERVER_WS_URL      wss://iomt.hospital.local/stream
  CARDIOAI_BACKEND_ID     cardioai-prod-01
  IOMT_SHARED_SECRET      <32+ char — from Vault/SSM>
  IOMT_JWT_SECRET         <32+ char — from Vault/SSM>

${BOLD}QUICK START${NC}
  # 1. Generate all artefacts
  ./deploy_iomt_cardioai.sh generate

  # 2. Fill in secrets
  cp deploy/.env.example deploy/.env && \$EDITOR deploy/.env

  # 3a. Docker single container
  export IOMT_SERVER_WS_URL=wss://... CARDIOAI_BACKEND_ID=... \\
         IOMT_SHARED_SECRET=... IOMT_JWT_SECRET=...
  ./deploy_iomt_cardioai.sh docker

  # 3b. Docker Compose (full stack)
  ./deploy_iomt_cardioai.sh compose

  # 3c. Kubernetes
  ./deploy_iomt_cardioai.sh k8s

  # 3d. Bare metal / VM
  sudo ./deploy_iomt_cardioai.sh systemd

  # 4. Verify
  ./deploy_iomt_cardioai.sh health

HELP
}

# =============================================================================
#  ENTRYPOINT
# =============================================================================
main() {
    local cmd="${1:-help}"
    case "${cmd}" in
        generate) cmd_generate ;;
        docker)   cmd_docker   ;;
        compose)  cmd_compose  ;;
        k8s)      cmd_k8s      ;;
        systemd)  cmd_systemd  ;;
        health)   cmd_health   ;;
        logs)     cmd_logs     ;;
        stop)     cmd_stop     ;;
        help|--help|-h) cmd_help ;;
        *)
            err "Unknown command: ${cmd}"
            cmd_help
            exit 1
            ;;
    esac
}

main "$@"
